[package]
name = "zj-docker"
version = "0.4.0"
authors = ["Lev Perschin", "Daniel Jankowski"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
zellij-tile = "0.42.2"
chrono = "0.4.40"
serde_json = "1.0.140"
rust-fuzzy-search = "0.1.1"
