[package]
name = "zj-docker"
version = "0.3.0"
authors = ["Lev Perschin", "Daniel Jankowski"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
zellij-tile = "0.41.1"
chrono = "0.4.38"
serde_json = "1.0.132"
rust-fuzzy-search = "0.1.1"
