[package]
name = "zj-docker"
version = "0.2.0"
authors = ["Lev Perschin", "Daniel Jankowski"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
zellij-tile = "0.39.0"
chrono = "0.4.0"
serde_json = "1.0.108"
rust-fuzzy-search = "0.1.1"
